# PATH MANAGEMENT

In [1]:
import os

print(os.getcwd())
if not os.getcwd().endswith("app"):
    os.chdir("../app")
    print(os.getcwd())

import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

%load_ext autoreload
%autoreload 2
# %matplotlib inline

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/notebooks
/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/app

In [2]:
from src.config import Configuration

CONFIG = Configuration(
    batch_size=8, # NOTE: CHANGE    
    max_tok_length=64, # NOTE: CHANGE
    max_epoch=10, # NOTE: CHANGE

    model_name="google/mt5-large"

    
)

# Fine-tuning

Fine-tuning refers to the process in transfer learning in which the parameter values of a model trained on a large dataset are modified when the training process continues on a small dataset (see [Kevin Murphy's book](https://probml.github.io/pml-book/book1.html) Section 19.2 for further details). The main motivation is to adapt a pre-trained model trained on a large amount of data to tackle a specific task providing better performance that would be achieved training on the small task-specific dataset.

In this notebook, we are going to use for fine-tuning a dataset set that is already available in the [Datasets repository](https://huggingface.co/datasets) from Hugging Face. However, the [Datasets library](https://huggingface.co/docs/datasets) makes easy to access and load datasets. For example, you can easily load your own dataset following [this tutorial](https://huggingface.co/docs/datasets/loading#local-and-remote-files).

More precisely, we are going to explain how to fine-tune the [NLLB model](https://huggingface.co/docs/transformers/model_doc/nllb) on the [Europarl-ST dataset](https://huggingface.co/datasets/tj-solergibert/Europarl-ST), but only that [dataset of Europarl-ST focused on the text data for MT from English](https://huggingface.co/datasets/tj-solergibert/Europarl-ST-processed-mt-en).

In [3]:
# from datasets import load_dataset

# raw_datasets = load_dataset("tj-solergibert/Europarl-ST-processed-mt-en")

# print(raw_datasets)

from src.data import get_es_eo_dataset

CONFIG.corpus_path = CONFIG.corpus_path_smaller  # NOTE: CHANGE
raw_datasets = get_es_eo_dataset(CONFIG)

print(raw_datasets)

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

DatasetDict({
    train: Dataset({
        features: ['source_text', 'dest_text', 'dest_lang'],
        num_rows: 20097
    })
    test: Dataset({
        features: ['source_text', 'dest_text', 'dest_lang'],
        num_rows: 4306
    })
    valid: Dataset({
        features: ['source_text', 'dest_text', 'dest_lang'],
        num_rows: 4306
    })
})

As shown, the Europarl-ST already comes with a pre-defined partition on the three conventional sets: training, validation and test. Each set is a dictionary with a list of source sentences (source_text), target sentences (dest_text) and the target language (dest_lang).

Let's take a closer look at the features of the training set:

In [4]:
raw_datasets["train"].features

{'source_text': Value('string'),
 'dest_text': Value('string'),
 'dest_lang': Value('int64')}

As you can see, the possible target languages are German, English, Spanish, French, Italian, Dutch, Polish, Portuguese and Romanian.

Let us take a look at the translations of the first two English sentences:

In [5]:
raw_datasets["train"][:14]["source_text"]

['luego se puso mi padre.',
 'para lo mejor o para lo peor',
 'zai jiam (creo que era así)',
 'el sol le vino de perlas para su cuidada melena rubia.',
 'considerando que las operaciones tales como angelfire y geo cities? han existido desde los primeros días de la web, las nuevas ofertas de, por ejemplo, facebook y my space? actualmente tiene muchos seguidores.',
 'sí, todos saben que es uno de los mejores centrocampistas atacantes ingleses de su generación.',
 'luego compiten en una batalla de baile contra tres jóvenes que visten ropa deportiva azul marca adidas.',
 'él tradujo algunos de mis poemas.',
 'museo manuel lópez villaseñor: contiene la obra del ciudadrealeño manuel lópez-villaseñor, uno de los máximos exponentes de la pintura española de la segunda mitad del siglo xx.',
 '¿quién es este ser que nos estás mostrando?',
 '(la película no debe tener lugar donde esté la cámara, el rodaje debe tener lugar donde la película tiene lugar).4.',
 'el pronombre de tercera persona neutro es det ‘ello’.',
 'aunque no podamos ver el sol.',
 'esto es lo que quería decir solamente…']

In [6]:

raw_datasets["train"][:14]["dest_text"]

['tiam mia patro sidiĝis.',
 'por pli bone aŭ for worse',
 'cao zhi (caŭ ĝi)',
 "parfumoj preparitaj por ŝia blonda har'.",
 'dum operacioj kiel ekzemple angelfire kaj geocities ekzistis ekde la fruaj tagoj de la reto, pli novaj proponoj de, ekzemple, facebook kaj twitter nuntempe havas grandajn sekvantajn.',
 'jes, ĉiuj scias, ke li estas unu el la plej bonaj anglaj atakantoj de sia generacio.',
 'poste ili danckonkursas kontraŭ tri junaj viroj kiuj estas vestitaj en bluaj sportvestoj de la marko adidas.',
 'li tradukis miajn poemojn',
 'muzeo manuel lópez-villaseñor: enhavas verkaro de la ciudadreala pentristo manuel lópez-villaseñor, nome unu el la ĉefaj reprezentantoj de la hispana realisma pentrarto de la dua duono de la 20a jarcento.',
 'kies letero estas tiu, kiun vi montris al mi?',
 '(la filmo ne okazu kie la kamerao staras; filmado okazu kie la filmo okazas.)',
 'sekse neŭtrala pronomo estas "ĝi".',
 'eĉ kiam la suno ne videblas.',
 'tion nur mi volas diri,']

In [7]:
raw_datasets["train"][:14]["dest_lang"]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

As shown, each English sentence is repeated for each of the seven target languages (0: 'de', 2: 'es', 3: 'fr', 4: 'it', 5: 'nl', 6: 'pl', 7: 'pt').

Provided that the NLLB model was pretrained on sentence pairs involving 200 languages, being one of the them the translation from English into Spanish, we are going to be filtering Europarl-ST only for English into Spanish using a simple [lambda function](https://realpython.com/python-lambda/) with the [Dataset.filter() function](https://huggingface.co/docs/datasets/v2.9.0/en/package_reference/main_classes#datasets.Dataset.filter).

In [8]:
# lang="es"
# lang_id = raw_datasets["train"].features["dest_lang"].names.index(lang)
# raw_datasets = raw_datasets.filter(lambda x: x["dest_lang"] == lang_id)

Now we load the pre-trained tokenizer for the NLLB model and apply it to the English-Spanish pair:

In [9]:
from transformers import AutoTokenizer

checkpoint = CONFIG.model_name
# mT5 doesn't use src_lang/tgt_lang parameters like NLLB
# It uses task prefixes instead
tokenizer = AutoTokenizer.from_pretrained(
    checkpoint, 
    padding=True, 
    pad_to_multiple_of=8, 
    truncation=True, 
    max_length=CONFIG.max_tok_length,
)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/venv/lib/python3.12/site-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

We can apply the tokenizer function to any dataset taking advantage that Hugging Face Datasets are [Apache Arrow](https://arrow.apache.org) files stored on the disk, so you only keep the samples you ask for loaded in memory.

To keep the data as a dataset, we will use the [Dataset.map() function](https://huggingface.co/docs/datasets/en/package_reference/main_classes#datasets.Dataset.map). This also allows us some extra flexibility, if we need more preprocessing done than just tokenization. The map() method works by applying a function on each element of the dataset.

In our case, each sample pair is going to be preprocessed according to the training needs of the model that is to be finetuned:

In [10]:
def preprocess_function(sample):
    # mT5 requires task prefix prepended to source text
    prefixed_sources = [CONFIG.task_prefix + text for text in sample["source_text"]]
    
    model_inputs = tokenizer(
        prefixed_sources, 
        text_target = sample["dest_text"],

        )
    return model_inputs

The way the Datasets library applies this processing is by adding new fields to the datasets, one for each key in the dictionary returned by the tokenize function, that is, *input_ids*, *attention_mask* and *labels*. We can check what the preprocess_function is doing with a small sample

In [11]:
sample = raw_datasets["train"].select(range(2))
model_input = preprocess_function({
    "source_text": list(sample["source_text"]),
    "dest_text": list(sample["dest_text"]),
})
print(model_input)

{'input_ids': [[37194, 702, 259, 29037, 288, 26609, 267, 1411, 1796, 303, 259, 55110, 658, 25160, 260, 1], [37194, 702, 259, 29037, 288, 26609, 267, 435, 707, 5541, 259, 268, 435, 707, 603, 723, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'labels': [[259, 21837, 11174, 86504, 68146, 23311, 260, 1], [519, 6744, 35144, 11718, 332, 48461, 265, 1]]}

In [12]:
for sample in model_input['input_ids']:
    print(tokenizer.convert_ids_to_tokens(sample))

['▁translate', '▁from', '▁', 'Spanish', '▁to', '▁Esperanto', ':', '▁lu', 'ego', '▁se', '▁', 'puso', '▁mi', '▁padre', '.', '</s>']
['▁translate', '▁from', '▁', 'Spanish', '▁to', '▁Esperanto', ':', '▁para', '▁lo', '▁mejor', '▁', 'o', '▁para', '▁lo', '▁pe', 'or', '</s>']

We can recover the source text by applying [batch_decode](https://huggingface.co/docs/transformers/en/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.batch_decode) of the tokenizer

In [13]:
tokenizer.batch_decode(model_input['input_ids'])

['translate from Spanish to Esperanto: luego se puso mi padre.</s>',
 'translate from Spanish to Esperanto: para lo mejor o para lo peor</s>']

Now, we can apply the preprocess_function to the raw datasets (training, validation and test):

In [14]:
tokenized_datasets = raw_datasets.map(preprocess_function, batched=True)

Map:   0%|                                                                                                                                          | 0/20097 [00:00<?, ? examples/s]

Map:  25%|██████████████████████████████▊                                                                                             | 5000/20097 [00:00<00:00, 20430.40 examples/s]

Map:  55%|███████████████████████████████████████████████████████████████████▎                                                       | 11000/20097 [00:00<00:00, 32431.17 examples/s]

Map:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 17000/20097 [00:00<00:00, 38633.75 examples/s]

Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20097/20097 [00:00<00:00, 29078.91 examples/s]

Map:   0%|                                                                                                                                           | 0/4306 [00:00<?, ? examples/s]

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4306/4306 [00:00<00:00, 45998.63 examples/s]

Map:   0%|                                                                                                                                           | 0/4306 [00:00<?, ? examples/s]

Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4306/4306 [00:00<00:00, 47309.22 examples/s]

We are going to filter the tokenized datasets by maximum number of tokens in source and target language:

In [15]:
tokenized_datasets = tokenized_datasets.filter(lambda x: len(x["input_ids"]) <= CONFIG.max_tok_length and len(x["labels"]) <= CONFIG.max_tok_length , desc=f"Discarding source and target sentences with more than {CONFIG.max_tok_length} tokens")

Discarding source and target sentences with more than 64 tokens:   0%|                                                                              | 0/20097 [00:00<?, ? examples/s]

Discarding source and target sentences with more than 64 tokens:  40%|█████████████████████████▍                                      | 8000/20097 [00:00<00:00, 62248.85 examples/s]

Discarding source and target sentences with more than 64 tokens:  80%|██████████████████████████████████████████████████▏            | 16000/20097 [00:00<00:00, 63614.56 examples/s]

Discarding source and target sentences with more than 64 tokens: 100%|███████████████████████████████████████████████████████████████| 20097/20097 [00:00<00:00, 63374.28 examples/s]

Discarding source and target sentences with more than 64 tokens:   0%|                                                                               | 0/4306 [00:00<?, ? examples/s]

Discarding source and target sentences with more than 64 tokens: 100%|█████████████████████████████████████████████████████████████████| 4306/4306 [00:00<00:00, 62554.28 examples/s]

Discarding source and target sentences with more than 64 tokens:   0%|                                                                               | 0/4306 [00:00<?, ? examples/s]

Discarding source and target sentences with more than 64 tokens: 100%|█████████████████████████████████████████████████████████████████| 4306/4306 [00:00<00:00, 60990.86 examples/s]

We can take a quick look at the length histogram in the source language:

In [16]:
dic = {}
for sample in tokenized_datasets['train']:
    sample_length = len(sample['input_ids'])
    if sample_length not in dic:
        dic[sample_length] = 1
    else:
        dic[sample_length] += 1 

for i in range(1,CONFIG.max_tok_length+1):
    if i in dic:
        print(f"{i:>2} {dic[i]:>3}")

10   5
11  28
12 139
13 364
14 678
15 949
16 1066
17 1148
18 1143
19 1033
20 987
21 820
22 732
23 659
24 587
25 549
26 457
27 421
28 388
29 352
30 334
31 299
32 285
33 276
34 274
35 211
36 245
37 245
38 208
39 194
40 199
41 178
42 182
43 191
44 162
45 174
46 159
47 160
48 150
49 169
50 152
51 155
52 112
53 135
54 123
55 126
56 119
57 108
58 101
59 102
60  95
61 102
62  74
63  79
64  76

Checking a sample after filtering by maximum number of tokens:

In [17]:
for sample in tokenized_datasets['train'].select(range(5)):
    print(sample['input_ids'])
    print(sample['attention_mask'])
    print(sample['labels'])

[37194, 702, 259, 29037, 288, 26609, 267, 1411, 1796, 303, 259, 55110, 658, 25160, 260, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[259, 21837, 11174, 86504, 68146, 23311, 260, 1]
[37194, 702, 259, 29037, 288, 26609, 267, 435, 707, 5541, 259, 268, 435, 707, 603, 723, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[519, 6744, 35144, 11718, 332, 48461, 265, 1]
[37194, 702, 259, 29037, 288, 26609, 267, 40075, 1359, 579, 274, 49260, 319, 3415, 259, 7590, 271, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[4195, 134397, 274, 297, 14238, 259, 14006, 271, 1]
[37194, 702, 259, 29037, 288, 26609, 267, 362, 3208, 340, 42598, 269, 393, 4276, 435, 517, 40110, 906, 31192, 377, 259, 81724, 260, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[51816, 1171, 14510, 13788, 519, 259, 24050, 262, 65656, 262, 588, 277, 260, 1]
[37194, 702, 259, 29037, 288, 26609, 267, 5910, 261, 1746, 259, 155099, 319, 655, 4889, 269, 595, 259, 16679, 7026, 27692, 8540, 74267, 2712, 95640, 299, 269, 517, 7723, 1434, 260, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[384, 263, 261, 8920, 4274, 122252, 263, 261, 513, 615, 259, 2447, 18308, 362, 283, 19949, 10172, 385, 60175, 385, 259, 10925, 18406, 269, 10294, 141197, 268, 260, 1]

bitsandbytes is a quantization library with a Transformers integration. With this integration, you can quantize a model to 8 or 4-bits and enable many other options by configuring the BitsAndBytesConfig class. For example, you can:

<ul>
<li>set load_in_4bit=True to quantize the model to 4-bits when you load it</li>
<li>set bnb_4bit_quant_type="nf4" to use a special 4-bit data type for weights initialized from a normal distribution</li>
<li>set bnb_4bit_use_double_quant=True to use a nested quantization scheme to quantize the already quantized weights</li>
<li>set bnb_4bit_compute_dtype=torch.bfloat16 to use bfloat16 for faster computation</li>
</ul>

In [18]:
import torch
from transformers import BitsAndBytesConfig

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)

Pass the quantization_config to the from_pretrained method.

In [19]:
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained(
    checkpoint,
    quantization_config=quantization_config
    )

Next, you should call the prepare_model_for_kbit_training() function to preprocess the quantized model for training.

In [20]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False, gradient_checkpointing_kwargs={'use_reentrant':False})

[LoRA (Low-Rank Adaptation of Large Language Models)](https://huggingface.co/docs/peft/task_guides/lora_based_methods) is a [parameter-efficient fine-tuning (PEFT)](https://huggingface.co/docs/peft/index) technique that significantly reduces the number of trainable parameters. It works by inserting a smaller number of new weights into the model and only these are trained. This makes training with LoRA much faster, memory-efficient, and produces smaller model weights (a few hundred MBs), which are easier to store and share.

Each PEFT method is defined by a PeftConfig class that stores all the important parameters for building a PeftModel. For example, to train with LoRA, load and create a LoraConfig class and specify the following parameters:

<ul>
<li>task_type: the task to train for (sequence-to-sequence language modeling in this case)</li>
<li>r: the dimension of the low-rank matrices</li>
<li>lora_alpha: the scaling factor for the low-rank matrices</li>
<li>target_modules: determine what set of parameters are adapted</li>
<li>lora_dropout: the dropout probability of the LoRA layers</li>
</ul>

In [21]:
from peft import LoraConfig, get_peft_model

config = LoraConfig(
    task_type="SEQ_2_SEQ_LM",
    r=32, # NOTE: CHANGE
    lora_alpha=64, # NOTE: CHANGE
    # mT5 uses different module names than NLLB
    # For mT5, attention modules are named: q, k, v, o (same as T5)
    target_modules=["q", "k", "v", "o"],
    lora_dropout=0.1, # NOTE: CHANGE
    bias="none",
)

Once LoRA and the quantization are setup, create a quantized PeftModel with the get_peft_model() function. It takes a quantized model and the LoraConfig containing the parameters for how to configure a model for training with LoRA.

In [22]:
lora_model = get_peft_model(model, config)
lora_model.print_trainable_parameters()

trainable params: 18,874,368 || all params: 1,248,455,680 || trainable%: 1.5118

The function that is responsible for putting together samples inside a batch is called a collate function. It is an argument you can pass when you build a DataLoader, the default being a function that will just convert your samples to PyTorch tensors and concatenate them. This is not possible in our case since the inputs we have are not all of the same size. We have deliberately postponed the padding, to only apply it as necessary on each batch and avoid having over-long inputs with a lot of padding.

To do this in practice, we have to define a collate function that will apply the correct amount of padding to the items of the dataset we want to batch together. Fortunately, the Transformers library provides us with such a function via DataCollatorForSeq2Seq that takes a tokenizer when you instantiate it (to know which padding token to use, and whether the model expects padding to be on the left or on the right of the inputs), so we will also need to instantiate the model first to provide it to the collate function:

In [23]:
from transformers import DataCollatorForSeq2Seq
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer, 
    model=lora_model, 
    pad_to_multiple_of=8
    )

## Evaluation

The last thing to define for our Seq2SeqTrainer is how to compute the metrics to evaluate the predictions of our model with respect to references. To this purpose, we use the [Evaluate library](https://huggingface.co/docs/evaluate) which includes the definition of generic and task-specific metrics. In our case, we use the [BLEU metric](https://huggingface.co/spaces/evaluate-metric/bleu), or to be more precise, [sacreBLEU](https://huggingface.co/spaces/evaluate-metric/sacrebleu). You can see a simple example of usage below:

:

In [24]:
from evaluate import load

metric_bleu = load("sacrebleu")
metric_comet = load("comet")
metric_chrf = load("chrf")

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/venv/lib/python3.12/site-packages/torchmetrics/utilities/imports.py:23: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution

Fetching 5 files:   0%|                                                                                                                                        | 0/5 [00:00<?, ?it/s]

Fetching 5 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 112750.11it/s]

Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.5.6. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`

Encoder model frozen.

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/venv/lib/python3.12/site-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']

We need to define a function compute_metrics to compute BLEU scores at each epoch. The example below performs a basic post-processing to decode the predictions into texts:

In [25]:
from torch.nn.utils.rnn import pad_sequence
import numpy as np
def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]

    return preds, labels

def compute_metrics_train(eval_preds):
    preds, labels = eval_preds

    # Convert to lists if coming from a datasets.Column
    if not isinstance(labels, list):
        labels = list(labels)
        
    if isinstance(preds, tuple):
        preds = preds[0]
    
    # NOTE: CHANGE 
    # Replace invalid token IDs in predictions to prevent OverflowError
    # Clip to valid range and handle any overflow issues
    vocab_size = len(tokenizer)
    preds = np.array(preds)
    preds = np.where(
        (preds < 0) | (preds >= vocab_size) | np.isnan(preds) | np.isinf(preds), 
        tokenizer.pad_token_id, 
        preds
    )
    preds = np.clip(preds, 0, vocab_size - 1).astype(np.int64)
    preds = preds.tolist()
    
    # Decode predictions
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace negative ids in the labels as we can't decode them.
    labels = [
        [tokenizer.pad_token_id if j < 0 else j for j in label]
        for label in labels
    ]
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result_chrf = metric_chrf.compute(
        predictions=decoded_preds, 
        references=decoded_labels
    )
    result = {
        "chrf": result_chrf["score"],
    }
    

    prediction_lens = [np.count_nonzero(np.array(pred) != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result


def compute_metrics(preds, labels, sources):

    # Convert to lists if coming from a datasets.Column
    if not isinstance(labels, list):
        labels = list(labels)
        
    if isinstance(preds, tuple):
        preds = preds[0]
    
    # NOTE: CHANGE 
    # Replace invalid token IDs in predictions to prevent OverflowError
    if hasattr(preds, '__iter__') and len(preds) > 0:
        # Check if preds contains tensors
        if hasattr(preds[0], 'tolist'):
            # Pad sequences to same length
            preds_padded = pad_sequence(
                [p if len(p.shape) > 0 else p.unsqueeze(0) for p in preds], 
                batch_first=True, 
                padding_value=tokenizer.pad_token_id
            )
            preds = preds_padded.cpu().numpy()
        else:
            preds = np.array(preds) if not isinstance(preds, np.ndarray) else preds
             
    # Clip to valid range and handle any overflow issues
    vocab_size = len(tokenizer)
    # preds = np.array(preds)
    preds = np.where((preds < 0) | (preds >= vocab_size) | np.isnan(preds) | np.isinf(preds), 
                     tokenizer.pad_token_id, 
                     preds)
    preds = np.clip(preds, 0, vocab_size - 1).astype(np.int64)
    preds = preds.tolist()
    
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace negative ids in the labels as we can't decode them.
    labels = [
        [tokenizer.pad_token_id if j < 0 else j for j in label]
        for label in labels
    ]
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    
    # Decode sources
    # decoded_sources = tokenizer.batch_decode(sources, skip_special_tokens=True)

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result_blue = metric_bleu.compute(
        predictions=decoded_preds, 
        references=decoded_labels
    )
    result_comet = metric_comet.compute(
        sources=sources,
        predictions=decoded_preds, 
        references=[label[0] for label in decoded_labels]  # COMET expects flat list, not nested
    )
    result_chrf = metric_chrf.compute(
        predictions=decoded_preds, 
        references=decoded_labels
    )
    result = {
        "bleu": result_blue["score"],
        "comet": result_comet["mean_score"],
        "chrf": result_chrf["score"]
    }

    prediction_lens = [np.count_nonzero(np.array(pred) != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

## Training

The first step before we can define our [Trainer](https://huggingface.co/docs/transformers/en/main_classes/trainer#trainer) is to define a [Seq2SeqTrainingArguments class](https://huggingface.co/docs/transformers/en/main_classes/trainer#transformers.Seq2SeqTrainingArguments) that will contain all the hyperparameters the Trainer will use for training and evaluation. The only compulsory argument you have to provide is a directory where the trained model will be saved, as well as the checkpoints along the way. For all the rest, you can set them depending on the recommendations from the model developers:

In [26]:
from transformers import Seq2SeqTrainingArguments

args = Seq2SeqTrainingArguments(
    CONFIG.output_model_dir,
    eval_strategy = "epoch",
    learning_rate=1e-4,
    per_device_train_batch_size=CONFIG.batch_size,
    per_device_eval_batch_size=CONFIG.batch_size,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=CONFIG.max_epoch,
    predict_with_generate=True,

    generation_max_length=CONFIG.max_tok_length,
    generation_num_beams=5, # NOTE: CHANGE
    metric_for_best_model="chrf",   # NOTE: CHANGE # Since you're using chrF
)

Once we have our model, we can define a Trainer by passing it all the objects constructed up to now — the model, the training_args, the training and validation datasets, the tokenizer, the data collator and the compute_metrics function:

In [27]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    lora_model,
    args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['valid'],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics_train
)

/tmp/ipykernel_318266/1397975236.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

To fine-tune the model on our dataset, we just have to call the [train() function](https://huggingface.co/docs/transformers/en/main_classes/trainer#transformers.Trainer.train) of our Trainer:

In [28]:
trainer.train()

TrainOutput(global_step=23080, training_loss=2.2484395699856394, metrics={'train_runtime': 10171.862, 'train_samples_per_second': 18.147, 'train_steps_per_second': 2.269, 'total_flos': 5.746253345164493e+16, 'train_loss': 2.2484395699856394, 'epoch': 10.0})

The training stop because pc got powered down... need to continue training jeje

The model seems to start overfitting when taking a look at the validations, we gona let it finish but me end up with worse results

In [29]:
import os
import glob

# Find the latest checkpoint in the output directory
checkpoint_dirs = glob.glob(os.path.join(CONFIG.output_model_dir, "checkpoint-*"))
if checkpoint_dirs:
    latest_checkpoint = max(checkpoint_dirs, key=lambda x: int(x.split("-")[-1]))
    print(f"Resuming training from checkpoint: {latest_checkpoint}")
    
    trainer.train(resume_from_checkpoint=latest_checkpoint)
else:
    print("No checkpoints found. Starting training from scratch.")
    trainer.train()

Resuming training from checkpoint: ../models/mt5-large-finetuned-es-to-eo/checkpoint-23080

In [30]:
# Save the final model
trainer.save_model(os.path.join(CONFIG.output_model_dir, "final_model"))

In [31]:
# Load the final model
from transformers import AutoModelForSeq2SeqLM
from peft import PeftModel

# Load the base model with quantization
base_model = AutoModelForSeq2SeqLM.from_pretrained(
    checkpoint,
    quantization_config=quantization_config
)

# Load the LoRA adapter weights
model = PeftModel.from_pretrained(
    base_model,
    os.path.join(CONFIG.output_model_dir, "final_model")
)

## Inference

At inference time, it is recommended to use [generate()](https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/text_generation#transformers.GenerationMixin.generate). This method takes care of encoding the input and feeding the encoded hidden states via cross-attention layers to the decoder and auto-regressively generates the decoder output. Check out [this blog post](https://huggingface.co/blog/how-to-generate) to know all the details about generating text with Transformers. There’s also [this blog post](https://huggingface.co/blog/encoder-decoder#encoder-decoder) which explains how generation works in general in encoder-decoder models.

Let us first load the default inference parameters of NLLB:

In [32]:
from transformers import GenerationConfig

generation_config = GenerationConfig.from_pretrained(
    checkpoint,
)

print(generation_config)

GenerationConfig {
  "decoder_start_token_id": 0,
  "eos_token_id": 1,
  "pad_token_id": 0
}

We prepare the test set in batches to be translated:

In [33]:
batch_tokenized_test = tokenized_datasets['test'].batch(CONFIG.batch_size)

Batching examples:   0%|                                                                | 0/3938 [00:00<?, ? examples/s]

Batching examples:  47%|███████████████████████▎                          | 1832/3938 [00:00<00:00, 18099.72 examples/s]

Batching examples:  93%|██████████████████████████████████████████████▌   | 3672/3938 [00:00<00:00, 18216.23 examples/s]

Batching examples: 100%|██████████████████████████████████████████████████| 3938/3938 [00:00<00:00, 17824.20 examples/s]

Processing in batches to add padding and converting to tensors, then perform inference with num_beams = 1 and do_sample = False, that is, greedy search.

In [34]:
import tqdm
number_of_batches = len(batch_tokenized_test["source_text"])
all_sources = []
output_sequences = []
for i in tqdm.tqdm(range(number_of_batches)):
    all_sources.extend(batch_tokenized_test["source_text"][i])

    inputs = tokenizer(
        batch_tokenized_test["source_text"][i], 
        max_length=CONFIG.max_tok_length, 
        truncation=True, 
        return_tensors="pt", 
        padding=True,
        )
    with torch.no_grad():    
        output_batch = model.generate(
            generation_config=generation_config, 
            input_ids=inputs["input_ids"].cuda(), 
            attention_mask=inputs["attention_mask"].cuda(), 
            forced_bos_token_id=tokenizer.convert_tokens_to_ids(CONFIG.tgt_code), 
            max_length = CONFIG.max_tok_length, 
            num_beams=1, 
            do_sample=False,
            )
    output_sequences.extend(output_batch.cpu())

  0%|                                                                                           | 0/493 [00:00<?, ?it/s]

  0%|▏                                                                                  | 1/493 [00:00<06:44,  1.22it/s]

  0%|▎                                                                                  | 2/493 [00:01<08:17,  1.01s/it]

  1%|▌                                                                                  | 3/493 [00:03<08:27,  1.04s/it]

  1%|▋                                                                                  | 4/493 [00:03<07:14,  1.13it/s]

  1%|▊                                                                                  | 5/493 [00:04<07:31,  1.08it/s]

  1%|█                                                                                  | 6/493 [00:05<08:25,  1.04s/it]

  1%|█▏                                                                                 | 7/493 [00:07<08:56,  1.10s/it]

  2%|█▎                                                                                 | 8/493 [00:08<08:13,  1.02s/it]

  2%|█▌                                                                                 | 9/493 [00:08<08:04,  1.00s/it]

  2%|█▋                                                                                | 10/493 [00:10<09:34,  1.19s/it]

  2%|█▊                                                                                | 11/493 [00:12<10:37,  1.32s/it]

  2%|█▉                                                                                | 12/493 [00:13<11:19,  1.41s/it]

  3%|██▏                                                                               | 13/493 [00:14<09:57,  1.25s/it]

  3%|██▎                                                                               | 14/493 [00:15<09:33,  1.20s/it]

  3%|██▍                                                                               | 15/493 [00:16<09:02,  1.13s/it]

  3%|██▋                                                                               | 16/493 [00:17<08:00,  1.01s/it]

  3%|██▊                                                                               | 17/493 [00:18<07:10,  1.11it/s]

  4%|██▉                                                                               | 18/493 [00:19<07:59,  1.01s/it]

  4%|███▏                                                                              | 19/493 [00:21<09:25,  1.19s/it]

  4%|███▎                                                                              | 20/493 [00:21<08:22,  1.06s/it]

  4%|███▍                                                                              | 21/493 [00:22<08:42,  1.11s/it]

  4%|███▋                                                                              | 22/493 [00:24<09:11,  1.17s/it]

  5%|███▊                                                                              | 23/493 [00:25<09:16,  1.18s/it]

  5%|███▉                                                                              | 24/493 [00:27<10:16,  1.31s/it]

  5%|████▏                                                                             | 25/493 [00:28<09:17,  1.19s/it]

  5%|████▎                                                                             | 26/493 [00:28<08:42,  1.12s/it]

  5%|████▍                                                                             | 27/493 [00:30<09:49,  1.26s/it]

  6%|████▋                                                                             | 28/493 [00:31<09:47,  1.26s/it]

  6%|████▊                                                                             | 29/493 [00:33<09:29,  1.23s/it]

  6%|████▉                                                                             | 30/493 [00:33<08:40,  1.12s/it]

  6%|█████▏                                                                            | 31/493 [00:34<08:11,  1.06s/it]

  6%|█████▎                                                                            | 32/493 [00:35<07:15,  1.06it/s]

  7%|█████▍                                                                            | 33/493 [00:37<08:46,  1.15s/it]

  7%|█████▋                                                                            | 34/493 [00:38<09:01,  1.18s/it]

  7%|█████▊                                                                            | 35/493 [00:39<08:48,  1.15s/it]

  7%|█████▉                                                                            | 36/493 [00:40<08:04,  1.06s/it]

  8%|██████▏                                                                           | 37/493 [00:41<08:39,  1.14s/it]

  8%|██████▎                                                                           | 38/493 [00:42<08:31,  1.12s/it]

  8%|██████▍                                                                           | 39/493 [00:43<08:32,  1.13s/it]

  8%|██████▋                                                                           | 40/493 [00:45<09:27,  1.25s/it]

  8%|██████▊                                                                           | 41/493 [00:47<10:17,  1.37s/it]

  9%|██████▉                                                                           | 42/493 [00:48<10:07,  1.35s/it]

  9%|███████▏                                                                          | 43/493 [00:49<09:40,  1.29s/it]

  9%|███████▎                                                                          | 44/493 [00:50<08:36,  1.15s/it]

  9%|███████▍                                                                          | 45/493 [00:51<09:40,  1.30s/it]

  9%|███████▋                                                                          | 46/493 [00:52<08:11,  1.10s/it]

 10%|███████▊                                                                          | 47/493 [00:53<07:32,  1.02s/it]

 10%|███████▉                                                                          | 48/493 [00:54<07:51,  1.06s/it]

 10%|████████▏                                                                         | 49/493 [00:56<09:06,  1.23s/it]

 10%|████████▎                                                                         | 50/493 [00:57<09:41,  1.31s/it]

 10%|████████▍                                                                         | 51/493 [00:59<10:01,  1.36s/it]

 11%|████████▋                                                                         | 52/493 [01:00<09:30,  1.29s/it]

 11%|████████▊                                                                         | 53/493 [01:01<08:22,  1.14s/it]

 11%|████████▉                                                                         | 54/493 [01:02<09:23,  1.28s/it]

 11%|█████████▏                                                                        | 55/493 [01:04<10:06,  1.38s/it]

 11%|█████████▎                                                                        | 56/493 [01:04<08:30,  1.17s/it]

 12%|█████████▍                                                                        | 57/493 [01:06<09:29,  1.31s/it]

 12%|█████████▋                                                                        | 58/493 [01:07<08:13,  1.13s/it]

 12%|█████████▊                                                                        | 59/493 [01:08<08:45,  1.21s/it]

 12%|█████████▉                                                                        | 60/493 [01:09<08:08,  1.13s/it]

 12%|██████████▏                                                                       | 61/493 [01:11<09:12,  1.28s/it]

 13%|██████████▎                                                                       | 62/493 [01:12<08:44,  1.22s/it]

 13%|██████████▍                                                                       | 63/493 [01:14<09:38,  1.34s/it]

 13%|██████████▋                                                                       | 64/493 [01:15<09:06,  1.27s/it]

 13%|██████████▊                                                                       | 65/493 [01:15<08:06,  1.14s/it]

 13%|██████████▉                                                                       | 66/493 [01:16<07:05,  1.00it/s]

 14%|███████████▏                                                                      | 67/493 [01:18<08:25,  1.19s/it]

 14%|███████████▎                                                                      | 68/493 [01:18<07:18,  1.03s/it]

 14%|███████████▍                                                                      | 69/493 [01:20<07:31,  1.07s/it]

 14%|███████████▋                                                                      | 70/493 [01:21<08:11,  1.16s/it]

 14%|███████████▊                                                                      | 71/493 [01:22<08:27,  1.20s/it]

 15%|███████████▉                                                                      | 72/493 [01:24<09:20,  1.33s/it]

 15%|████████████▏                                                                     | 73/493 [01:25<09:18,  1.33s/it]

 15%|████████████▎                                                                     | 74/493 [01:26<08:30,  1.22s/it]

 15%|████████████▍                                                                     | 75/493 [01:28<09:22,  1.34s/it]

 15%|████████████▋                                                                     | 76/493 [01:29<08:27,  1.22s/it]

 16%|████████████▊                                                                     | 77/493 [01:29<07:30,  1.08s/it]

 16%|████████████▉                                                                     | 78/493 [01:31<08:36,  1.24s/it]

 16%|█████████████▏                                                                    | 79/493 [01:32<08:42,  1.26s/it]

 16%|█████████████▎                                                                    | 80/493 [01:33<07:52,  1.14s/it]

 16%|█████████████▍                                                                    | 81/493 [01:35<08:10,  1.19s/it]

 17%|█████████████▋                                                                    | 82/493 [01:36<08:26,  1.23s/it]

 17%|█████████████▊                                                                    | 83/493 [01:37<08:33,  1.25s/it]

 17%|█████████████▉                                                                    | 84/493 [01:39<09:17,  1.36s/it]

 17%|██████████████▏                                                                   | 85/493 [01:40<09:26,  1.39s/it]

 17%|██████████████▎                                                                   | 86/493 [01:41<08:37,  1.27s/it]

 18%|██████████████▍                                                                   | 87/493 [01:42<08:29,  1.26s/it]

 18%|██████████████▋                                                                   | 88/493 [01:44<08:21,  1.24s/it]

 18%|██████████████▊                                                                   | 89/493 [01:44<07:12,  1.07s/it]

 18%|██████████████▉                                                                   | 90/493 [01:45<06:40,  1.01it/s]

 18%|███████████████▏                                                                  | 91/493 [01:46<07:03,  1.05s/it]

 19%|███████████████▎                                                                  | 92/493 [01:47<06:55,  1.04s/it]

 19%|███████████████▍                                                                  | 93/493 [01:49<07:49,  1.17s/it]

 19%|███████████████▋                                                                  | 94/493 [01:50<07:34,  1.14s/it]

 19%|███████████████▊                                                                  | 95/493 [01:51<07:43,  1.16s/it]

 19%|███████████████▉                                                                  | 96/493 [01:52<07:28,  1.13s/it]

 20%|████████████████▏                                                                 | 97/493 [01:53<07:45,  1.18s/it]

 20%|████████████████▎                                                                 | 98/493 [01:54<07:25,  1.13s/it]

 20%|████████████████▍                                                                 | 99/493 [01:56<07:55,  1.21s/it]

 20%|████████████████▍                                                                | 100/493 [01:57<07:14,  1.10s/it]

 20%|████████████████▌                                                                | 101/493 [01:58<06:54,  1.06s/it]

 21%|████████████████▊                                                                | 102/493 [01:59<07:04,  1.09s/it]

 21%|████████████████▉                                                                | 103/493 [02:00<07:45,  1.19s/it]

 21%|█████████████████                                                                | 104/493 [02:02<07:51,  1.21s/it]

 21%|█████████████████▎                                                               | 105/493 [02:02<07:00,  1.09s/it]

 22%|█████████████████▍                                                               | 106/493 [02:04<07:38,  1.18s/it]

 22%|█████████████████▌                                                               | 107/493 [02:05<08:29,  1.32s/it]

 22%|█████████████████▋                                                               | 108/493 [02:07<09:03,  1.41s/it]

 22%|█████████████████▉                                                               | 109/493 [02:09<09:25,  1.47s/it]

 22%|██████████████████                                                               | 110/493 [02:09<08:05,  1.27s/it]

 23%|██████████████████▏                                                              | 111/493 [02:11<07:59,  1.25s/it]

 23%|██████████████████▍                                                              | 112/493 [02:12<07:30,  1.18s/it]

 23%|██████████████████▌                                                              | 113/493 [02:13<07:29,  1.18s/it]

 23%|██████████████████▋                                                              | 114/493 [02:14<07:54,  1.25s/it]

 23%|██████████████████▉                                                              | 115/493 [02:16<08:37,  1.37s/it]

 24%|███████████████████                                                              | 116/493 [02:17<08:45,  1.39s/it]

 24%|███████████████████▏                                                             | 117/493 [02:18<07:49,  1.25s/it]

 24%|███████████████████▍                                                             | 118/493 [02:19<06:30,  1.04s/it]

 24%|███████████████████▌                                                             | 119/493 [02:20<06:20,  1.02s/it]

 24%|███████████████████▋                                                             | 120/493 [02:21<06:28,  1.04s/it]

 25%|███████████████████▉                                                             | 121/493 [02:22<07:04,  1.14s/it]

 25%|████████████████████                                                             | 122/493 [02:24<07:37,  1.23s/it]

 25%|████████████████████▏                                                            | 123/493 [02:25<07:05,  1.15s/it]

 25%|████████████████████▎                                                            | 124/493 [02:26<07:57,  1.29s/it]

 25%|████████████████████▌                                                            | 125/493 [02:28<07:51,  1.28s/it]

 26%|████████████████████▋                                                            | 126/493 [02:29<08:00,  1.31s/it]

 26%|████████████████████▊                                                            | 127/493 [02:30<07:40,  1.26s/it]

 26%|█████████████████████                                                            | 128/493 [02:31<07:28,  1.23s/it]

 26%|█████████████████████▏                                                           | 129/493 [02:33<08:10,  1.35s/it]

 26%|█████████████████████▎                                                           | 130/493 [02:34<07:47,  1.29s/it]

 27%|█████████████████████▌                                                           | 131/493 [02:35<07:18,  1.21s/it]

 27%|█████████████████████▋                                                           | 132/493 [02:36<07:07,  1.18s/it]

 27%|█████████████████████▊                                                           | 133/493 [02:38<08:08,  1.36s/it]

 27%|██████████████████████                                                           | 134/493 [02:39<07:56,  1.33s/it]

 27%|██████████████████████▏                                                          | 135/493 [02:41<08:11,  1.37s/it]

 28%|██████████████████████▎                                                          | 136/493 [02:42<08:02,  1.35s/it]

 28%|██████████████████████▌                                                          | 137/493 [02:43<07:12,  1.22s/it]

 28%|██████████████████████▋                                                          | 138/493 [02:44<06:58,  1.18s/it]

 28%|██████████████████████▊                                                          | 139/493 [02:45<06:41,  1.13s/it]

 28%|███████████████████████                                                          | 140/493 [02:46<07:03,  1.20s/it]

 29%|███████████████████████▏                                                         | 141/493 [02:48<07:13,  1.23s/it]

 29%|███████████████████████▎                                                         | 142/493 [02:48<06:27,  1.10s/it]

 29%|███████████████████████▍                                                         | 143/493 [02:50<07:20,  1.26s/it]

 29%|███████████████████████▋                                                         | 144/493 [02:51<07:26,  1.28s/it]

 29%|███████████████████████▊                                                         | 145/493 [02:53<07:41,  1.33s/it]

 30%|███████████████████████▉                                                         | 146/493 [02:54<08:09,  1.41s/it]

 30%|████████████████████████▏                                                        | 147/493 [02:56<08:30,  1.48s/it]

 30%|████████████████████████▎                                                        | 148/493 [02:57<06:59,  1.21s/it]

 30%|████████████████████████▍                                                        | 149/493 [02:58<07:40,  1.34s/it]

 30%|████████████████████████▋                                                        | 150/493 [03:00<07:36,  1.33s/it]

 31%|████████████████████████▊                                                        | 151/493 [03:01<07:04,  1.24s/it]

 31%|████████████████████████▉                                                        | 152/493 [03:02<07:03,  1.24s/it]

 31%|█████████████████████████▏                                                       | 153/493 [03:03<06:40,  1.18s/it]

 31%|█████████████████████████▎                                                       | 154/493 [03:04<06:28,  1.15s/it]

 31%|█████████████████████████▍                                                       | 155/493 [03:05<05:48,  1.03s/it]

 32%|█████████████████████████▋                                                       | 156/493 [03:06<05:45,  1.03s/it]

 32%|█████████████████████████▊                                                       | 157/493 [03:07<05:59,  1.07s/it]

 32%|█████████████████████████▉                                                       | 158/493 [03:08<05:43,  1.03s/it]

 32%|██████████████████████████                                                       | 159/493 [03:09<06:18,  1.13s/it]

 32%|██████████████████████████▎                                                      | 160/493 [03:10<05:49,  1.05s/it]

 33%|██████████████████████████▍                                                      | 161/493 [03:11<05:25,  1.02it/s]

 33%|██████████████████████████▌                                                      | 162/493 [03:12<05:58,  1.08s/it]

 33%|██████████████████████████▊                                                      | 163/493 [03:14<06:51,  1.25s/it]

 33%|██████████████████████████▉                                                      | 164/493 [03:15<07:27,  1.36s/it]

 33%|███████████████████████████                                                      | 165/493 [03:17<07:12,  1.32s/it]

 34%|███████████████████████████▎                                                     | 166/493 [03:18<07:42,  1.42s/it]

 34%|███████████████████████████▍                                                     | 167/493 [03:19<07:16,  1.34s/it]

 34%|███████████████████████████▌                                                     | 168/493 [03:21<07:25,  1.37s/it]

 34%|███████████████████████████▊                                                     | 169/493 [03:23<07:48,  1.45s/it]

 34%|███████████████████████████▉                                                     | 170/493 [03:24<08:03,  1.50s/it]

 35%|████████████████████████████                                                     | 171/493 [03:25<07:12,  1.34s/it]

 35%|████████████████████████████▎                                                    | 172/493 [03:27<07:24,  1.39s/it]

 35%|████████████████████████████▍                                                    | 173/493 [03:28<07:28,  1.40s/it]

 35%|████████████████████████████▌                                                    | 174/493 [03:30<07:30,  1.41s/it]

 35%|████████████████████████████▊                                                    | 175/493 [03:31<07:51,  1.48s/it]

 36%|████████████████████████████▉                                                    | 176/493 [03:32<06:59,  1.32s/it]

 36%|█████████████████████████████                                                    | 177/493 [03:33<06:30,  1.24s/it]

 36%|█████████████████████████████▏                                                   | 178/493 [03:34<06:26,  1.23s/it]

 36%|█████████████████████████████▍                                                   | 179/493 [03:36<06:33,  1.25s/it]

 37%|█████████████████████████████▌                                                   | 180/493 [03:37<06:27,  1.24s/it]

 37%|█████████████████████████████▋                                                   | 181/493 [03:38<06:32,  1.26s/it]

 37%|█████████████████████████████▉                                                   | 182/493 [03:40<06:46,  1.31s/it]

 37%|██████████████████████████████                                                   | 183/493 [03:41<06:28,  1.25s/it]

 37%|██████████████████████████████▏                                                  | 184/493 [03:42<06:03,  1.18s/it]

 38%|██████████████████████████████▍                                                  | 185/493 [03:43<05:59,  1.17s/it]

 38%|██████████████████████████████▌                                                  | 186/493 [03:43<05:02,  1.01it/s]

 38%|██████████████████████████████▋                                                  | 187/493 [03:45<05:12,  1.02s/it]

 38%|██████████████████████████████▉                                                  | 188/493 [03:46<06:07,  1.21s/it]

 38%|███████████████████████████████                                                  | 189/493 [03:48<06:28,  1.28s/it]

 39%|███████████████████████████████▏                                                 | 190/493 [03:49<06:58,  1.38s/it]

 39%|███████████████████████████████▍                                                 | 191/493 [03:51<07:19,  1.46s/it]

 39%|███████████████████████████████▌                                                 | 192/493 [03:52<07:01,  1.40s/it]

 39%|███████████████████████████████▋                                                 | 193/493 [03:53<06:00,  1.20s/it]

 39%|███████████████████████████████▊                                                 | 194/493 [03:55<06:38,  1.33s/it]

 40%|████████████████████████████████                                                 | 195/493 [03:56<06:14,  1.26s/it]

 40%|████████████████████████████████▏                                                | 196/493 [03:56<05:22,  1.09s/it]

 40%|████████████████████████████████▎                                                | 197/493 [03:57<05:22,  1.09s/it]

 40%|████████████████████████████████▌                                                | 198/493 [03:58<05:19,  1.08s/it]

 40%|████████████████████████████████▋                                                | 199/493 [03:59<05:08,  1.05s/it]

 41%|████████████████████████████████▊                                                | 200/493 [04:01<05:21,  1.10s/it]

 41%|█████████████████████████████████                                                | 201/493 [04:01<04:38,  1.05it/s]

 41%|█████████████████████████████████▏                                               | 202/493 [04:03<05:02,  1.04s/it]

 41%|█████████████████████████████████▎                                               | 203/493 [04:03<04:42,  1.03it/s]

 41%|█████████████████████████████████▌                                               | 204/493 [04:04<04:10,  1.15it/s]

 42%|█████████████████████████████████▋                                               | 205/493 [04:05<04:45,  1.01it/s]

 42%|█████████████████████████████████▊                                               | 206/493 [04:06<04:31,  1.06it/s]

 42%|██████████████████████████████████                                               | 207/493 [04:07<05:01,  1.05s/it]

 42%|██████████████████████████████████▏                                              | 208/493 [04:09<05:46,  1.21s/it]

 42%|██████████████████████████████████▎                                              | 209/493 [04:10<05:23,  1.14s/it]

 43%|██████████████████████████████████▌                                              | 210/493 [04:11<05:24,  1.15s/it]

 43%|██████████████████████████████████▋                                              | 211/493 [04:12<04:52,  1.04s/it]

 43%|██████████████████████████████████▊                                              | 212/493 [04:13<04:38,  1.01it/s]

 43%|██████████████████████████████████▉                                              | 213/493 [04:14<05:09,  1.10s/it]

 43%|███████████████████████████████████▏                                             | 214/493 [04:15<05:11,  1.12s/it]

 44%|███████████████████████████████████▎                                             | 215/493 [04:17<05:27,  1.18s/it]

 44%|███████████████████████████████████▍                                             | 216/493 [04:18<06:03,  1.31s/it]

 44%|███████████████████████████████████▋                                             | 217/493 [04:19<05:56,  1.29s/it]

 44%|███████████████████████████████████▊                                             | 218/493 [04:21<06:17,  1.37s/it]

 44%|███████████████████████████████████▉                                             | 219/493 [04:22<05:11,  1.14s/it]

 45%|████████████████████████████████████▏                                            | 220/493 [04:23<05:49,  1.28s/it]

 45%|████████████████████████████████████▎                                            | 221/493 [04:25<05:59,  1.32s/it]

 45%|████████████████████████████████████▍                                            | 222/493 [04:26<05:34,  1.23s/it]

 45%|████████████████████████████████████▋                                            | 223/493 [04:27<06:04,  1.35s/it]

 45%|████████████████████████████████████▊                                            | 224/493 [04:29<06:24,  1.43s/it]

 46%|████████████████████████████████████▉                                            | 225/493 [04:31<06:39,  1.49s/it]

 46%|█████████████████████████████████████▏                                           | 226/493 [04:32<06:48,  1.53s/it]

 46%|█████████████████████████████████████▎                                           | 227/493 [04:33<06:01,  1.36s/it]

 46%|█████████████████████████████████████▍                                           | 228/493 [04:34<06:00,  1.36s/it]

 46%|█████████████████████████████████████▌                                           | 229/493 [04:36<06:20,  1.44s/it]

 47%|█████████████████████████████████████▊                                           | 230/493 [04:37<05:40,  1.29s/it]

 47%|█████████████████████████████████████▉                                           | 231/493 [04:38<05:43,  1.31s/it]

 47%|██████████████████████████████████████                                           | 232/493 [04:40<06:07,  1.41s/it]

 47%|██████████████████████████████████████▎                                          | 233/493 [04:41<05:43,  1.32s/it]

 47%|██████████████████████████████████████▍                                          | 234/493 [04:42<05:25,  1.26s/it]

 48%|██████████████████████████████████████▌                                          | 235/493 [04:43<05:06,  1.19s/it]

 48%|██████████████████████████████████████▊                                          | 236/493 [04:44<04:54,  1.14s/it]

 48%|██████████████████████████████████████▉                                          | 237/493 [04:45<04:45,  1.12s/it]

 48%|███████████████████████████████████████                                          | 238/493 [04:46<04:07,  1.03it/s]

 48%|███████████████████████████████████████▎                                         | 239/493 [04:47<04:28,  1.06s/it]

 49%|███████████████████████████████████████▍                                         | 240/493 [04:48<04:37,  1.09s/it]

 49%|███████████████████████████████████████▌                                         | 241/493 [04:50<04:51,  1.16s/it]

 49%|███████████████████████████████████████▊                                         | 242/493 [04:51<05:24,  1.29s/it]

 49%|███████████████████████████████████████▉                                         | 243/493 [04:52<05:02,  1.21s/it]

 49%|████████████████████████████████████████                                         | 244/493 [04:53<04:42,  1.13s/it]

 50%|████████████████████████████████████████▎                                        | 245/493 [04:55<05:17,  1.28s/it]

 50%|████████████████████████████████████████▍                                        | 246/493 [04:56<05:28,  1.33s/it]

 50%|████████████████████████████████████████▌                                        | 247/493 [04:57<04:59,  1.22s/it]

 50%|████████████████████████████████████████▋                                        | 248/493 [04:58<04:26,  1.09s/it]

 51%|████████████████████████████████████████▉                                        | 249/493 [04:59<04:16,  1.05s/it]

 51%|█████████████████████████████████████████                                        | 250/493 [05:00<04:21,  1.08s/it]

 51%|█████████████████████████████████████████▏                                       | 251/493 [05:02<04:50,  1.20s/it]

 51%|█████████████████████████████████████████▍                                       | 252/493 [05:03<05:20,  1.33s/it]

 51%|█████████████████████████████████████████▌                                       | 253/493 [05:05<05:13,  1.31s/it]

 52%|█████████████████████████████████████████▋                                       | 254/493 [05:06<05:06,  1.28s/it]

 52%|█████████████████████████████████████████▉                                       | 255/493 [05:07<05:14,  1.32s/it]

 52%|██████████████████████████████████████████                                       | 256/493 [05:08<04:22,  1.11s/it]

 52%|██████████████████████████████████████████▏                                      | 257/493 [05:09<03:58,  1.01s/it]

 52%|██████████████████████████████████████████▍                                      | 258/493 [05:10<04:41,  1.20s/it]

 53%|██████████████████████████████████████████▌                                      | 259/493 [05:11<04:11,  1.08s/it]

 53%|██████████████████████████████████████████▋                                      | 260/493 [05:12<04:20,  1.12s/it]

 53%|██████████████████████████████████████████▉                                      | 261/493 [05:14<04:35,  1.19s/it]

 53%|███████████████████████████████████████████                                      | 262/493 [05:15<04:15,  1.11s/it]

 53%|███████████████████████████████████████████▏                                     | 263/493 [05:16<04:50,  1.26s/it]

 54%|███████████████████████████████████████████▍                                     | 264/493 [05:17<04:36,  1.21s/it]

 54%|███████████████████████████████████████████▌                                     | 265/493 [05:18<04:33,  1.20s/it]

 54%|███████████████████████████████████████████▋                                     | 266/493 [05:20<04:35,  1.21s/it]

 54%|███████████████████████████████████████████▊                                     | 267/493 [05:21<05:02,  1.34s/it]

 54%|████████████████████████████████████████████                                     | 268/493 [05:23<05:21,  1.43s/it]

 55%|████████████████████████████████████████████▏                                    | 269/493 [05:24<05:04,  1.36s/it]

 55%|████████████████████████████████████████████▎                                    | 270/493 [05:26<05:08,  1.38s/it]

 55%|████████████████████████████████████████████▌                                    | 271/493 [05:26<04:31,  1.22s/it]

 55%|████████████████████████████████████████████▋                                    | 272/493 [05:28<04:57,  1.34s/it]

 55%|████████████████████████████████████████████▊                                    | 273/493 [05:30<05:13,  1.43s/it]

 56%|█████████████████████████████████████████████                                    | 274/493 [05:31<05:06,  1.40s/it]

 56%|█████████████████████████████████████████████▏                                   | 275/493 [05:32<04:47,  1.32s/it]

 56%|█████████████████████████████████████████████▎                                   | 276/493 [05:33<04:36,  1.27s/it]

 56%|█████████████████████████████████████████████▌                                   | 277/493 [05:34<04:12,  1.17s/it]

 56%|█████████████████████████████████████████████▋                                   | 278/493 [05:36<04:17,  1.20s/it]

 57%|█████████████████████████████████████████████▊                                   | 279/493 [05:37<04:25,  1.24s/it]

 57%|██████████████████████████████████████████████                                   | 280/493 [05:38<04:48,  1.35s/it]

 57%|██████████████████████████████████████████████▏                                  | 281/493 [05:39<04:21,  1.24s/it]

 57%|██████████████████████████████████████████████▎                                  | 282/493 [05:41<04:30,  1.28s/it]

 57%|██████████████████████████████████████████████▍                                  | 283/493 [05:42<04:19,  1.24s/it]

 58%|██████████████████████████████████████████████▋                                  | 284/493 [05:43<03:48,  1.09s/it]

 58%|██████████████████████████████████████████████▊                                  | 285/493 [05:43<03:14,  1.07it/s]

 58%|██████████████████████████████████████████████▉                                  | 286/493 [05:44<03:22,  1.02it/s]

 58%|███████████████████████████████████████████████▏                                 | 287/493 [05:45<03:29,  1.02s/it]

 58%|███████████████████████████████████████████████▎                                 | 288/493 [05:47<03:37,  1.06s/it]

 59%|███████████████████████████████████████████████▍                                 | 289/493 [05:48<03:28,  1.02s/it]

 59%|███████████████████████████████████████████████▋                                 | 290/493 [05:49<03:47,  1.12s/it]

 59%|███████████████████████████████████████████████▊                                 | 291/493 [05:50<03:40,  1.09s/it]

 59%|███████████████████████████████████████████████▉                                 | 292/493 [05:51<03:33,  1.06s/it]

 59%|████████████████████████████████████████████████▏                                | 293/493 [05:52<03:32,  1.06s/it]

 60%|████████████████████████████████████████████████▎                                | 294/493 [05:53<03:21,  1.01s/it]

 60%|████████████████████████████████████████████████▍                                | 295/493 [05:54<03:31,  1.07s/it]

 60%|████████████████████████████████████████████████▋                                | 296/493 [05:56<04:04,  1.24s/it]

 60%|████████████████████████████████████████████████▊                                | 297/493 [05:57<03:42,  1.14s/it]

 60%|████████████████████████████████████████████████▉                                | 298/493 [05:58<03:35,  1.10s/it]

 61%|█████████████████████████████████████████████████▏                               | 299/493 [05:59<03:20,  1.03s/it]

 61%|█████████████████████████████████████████████████▎                               | 300/493 [05:59<03:04,  1.05it/s]

 61%|█████████████████████████████████████████████████▍                               | 301/493 [06:01<03:42,  1.16s/it]

 61%|█████████████████████████████████████████████████▌                               | 302/493 [06:03<04:09,  1.31s/it]

 61%|█████████████████████████████████████████████████▊                               | 303/493 [06:04<04:00,  1.27s/it]

 62%|█████████████████████████████████████████████████▉                               | 304/493 [06:05<03:50,  1.22s/it]

 62%|██████████████████████████████████████████████████                               | 305/493 [06:05<03:09,  1.01s/it]

 62%|██████████████████████████████████████████████████▎                              | 306/493 [06:07<03:43,  1.19s/it]

 62%|██████████████████████████████████████████████████▍                              | 307/493 [06:08<03:37,  1.17s/it]

 62%|██████████████████████████████████████████████████▌                              | 308/493 [06:09<03:48,  1.23s/it]

 63%|██████████████████████████████████████████████████▊                              | 309/493 [06:11<04:08,  1.35s/it]

 63%|██████████████████████████████████████████████████▉                              | 310/493 [06:12<04:01,  1.32s/it]

 63%|███████████████████████████████████████████████████                              | 311/493 [06:14<04:16,  1.41s/it]

 63%|███████████████████████████████████████████████████▎                             | 312/493 [06:16<04:26,  1.47s/it]

 63%|███████████████████████████████████████████████████▍                             | 313/493 [06:17<04:29,  1.50s/it]

 64%|███████████████████████████████████████████████████▌                             | 314/493 [06:19<04:21,  1.46s/it]

 64%|███████████████████████████████████████████████████▊                             | 315/493 [06:19<03:46,  1.27s/it]

 64%|███████████████████████████████████████████████████▉                             | 316/493 [06:21<03:49,  1.30s/it]

 64%|████████████████████████████████████████████████████                             | 317/493 [06:22<03:29,  1.19s/it]

 65%|████████████████████████████████████████████████████▏                            | 318/493 [06:23<03:14,  1.11s/it]

 65%|████████████████████████████████████████████████████▍                            | 319/493 [06:23<02:50,  1.02it/s]

 65%|████████████████████████████████████████████████████▌                            | 320/493 [06:24<02:35,  1.11it/s]

 65%|████████████████████████████████████████████████████▋                            | 321/493 [06:26<03:11,  1.11s/it]

 65%|████████████████████████████████████████████████████▉                            | 322/493 [06:27<03:11,  1.12s/it]

 66%|█████████████████████████████████████████████████████                            | 323/493 [06:28<03:35,  1.27s/it]

 66%|█████████████████████████████████████████████████████▏                           | 324/493 [06:30<03:50,  1.37s/it]

 66%|█████████████████████████████████████████████████████▍                           | 325/493 [06:31<03:49,  1.36s/it]

 66%|█████████████████████████████████████████████████████▌                           | 326/493 [06:32<03:23,  1.22s/it]

 66%|█████████████████████████████████████████████████████▋                           | 327/493 [06:33<03:24,  1.23s/it]

 67%|█████████████████████████████████████████████████████▉                           | 328/493 [06:35<03:43,  1.36s/it]

 67%|██████████████████████████████████████████████████████                           | 329/493 [06:36<03:41,  1.35s/it]

 67%|██████████████████████████████████████████████████████▏                          | 330/493 [06:38<03:53,  1.43s/it]

 67%|██████████████████████████████████████████████████████▍                          | 331/493 [06:39<03:29,  1.29s/it]

 67%|██████████████████████████████████████████████████████▌                          | 332/493 [06:40<03:22,  1.26s/it]

 68%|██████████████████████████████████████████████████████▋                          | 333/493 [06:42<03:25,  1.29s/it]

 68%|██████████████████████████████████████████████████████▉                          | 334/493 [06:42<02:57,  1.11s/it]

 68%|███████████████████████████████████████████████████████                          | 335/493 [06:43<02:50,  1.08s/it]

 68%|███████████████████████████████████████████████████████▏                         | 336/493 [06:45<03:15,  1.24s/it]

 68%|███████████████████████████████████████████████████████▎                         | 337/493 [06:46<03:07,  1.20s/it]

 69%|███████████████████████████████████████████████████████▌                         | 338/493 [06:47<03:12,  1.24s/it]

 69%|███████████████████████████████████████████████████████▋                         | 339/493 [06:49<03:10,  1.23s/it]

 69%|███████████████████████████████████████████████████████▊                         | 340/493 [06:50<03:20,  1.31s/it]

 69%|████████████████████████████████████████████████████████                         | 341/493 [06:51<03:16,  1.30s/it]

 69%|████████████████████████████████████████████████████████▏                        | 342/493 [06:53<03:14,  1.29s/it]

 70%|████████████████████████████████████████████████████████▎                        | 343/493 [06:54<03:00,  1.21s/it]

 70%|████████████████████████████████████████████████████████▌                        | 344/493 [06:55<02:53,  1.16s/it]

 70%|████████████████████████████████████████████████████████▋                        | 345/493 [06:56<02:53,  1.18s/it]

 70%|████████████████████████████████████████████████████████▊                        | 346/493 [06:57<03:12,  1.31s/it]

 70%|█████████████████████████████████████████████████████████                        | 347/493 [06:59<03:03,  1.26s/it]

 71%|█████████████████████████████████████████████████████████▏                       | 348/493 [07:00<03:19,  1.37s/it]

 71%|█████████████████████████████████████████████████████████▎                       | 349/493 [07:02<03:28,  1.45s/it]

 71%|█████████████████████████████████████████████████████████▌                       | 350/493 [07:04<03:35,  1.51s/it]

 71%|█████████████████████████████████████████████████████████▋                       | 351/493 [07:05<03:23,  1.44s/it]

 71%|█████████████████████████████████████████████████████████▊                       | 352/493 [07:06<03:12,  1.36s/it]

 72%|█████████████████████████████████████████████████████████▉                       | 353/493 [07:07<02:53,  1.24s/it]

 72%|██████████████████████████████████████████████████████████▏                      | 354/493 [07:09<03:08,  1.36s/it]

 72%|██████████████████████████████████████████████████████████▎                      | 355/493 [07:10<03:15,  1.42s/it]

 72%|██████████████████████████████████████████████████████████▍                      | 356/493 [07:11<03:05,  1.36s/it]

 72%|██████████████████████████████████████████████████████████▋                      | 357/493 [07:12<02:51,  1.26s/it]

 73%|██████████████████████████████████████████████████████████▊                      | 358/493 [07:14<02:51,  1.27s/it]

 73%|██████████████████████████████████████████████████████████▉                      | 359/493 [07:15<02:48,  1.26s/it]

 73%|███████████████████████████████████████████████████████████▏                     | 360/493 [07:16<02:48,  1.27s/it]

 73%|███████████████████████████████████████████████████████████▎                     | 361/493 [07:17<02:42,  1.23s/it]

 73%|███████████████████████████████████████████████████████████▍                     | 362/493 [07:19<02:39,  1.22s/it]

 74%|███████████████████████████████████████████████████████████▋                     | 363/493 [07:20<02:38,  1.22s/it]

 74%|███████████████████████████████████████████████████████████▊                     | 364/493 [07:21<02:52,  1.34s/it]

 74%|███████████████████████████████████████████████████████████▉                     | 365/493 [07:23<03:01,  1.42s/it]

 74%|████████████████████████████████████████████████████████████▏                    | 366/493 [07:24<02:45,  1.30s/it]

 74%|████████████████████████████████████████████████████████████▎                    | 367/493 [07:25<02:36,  1.24s/it]

 75%|████████████████████████████████████████████████████████████▍                    | 368/493 [07:27<02:43,  1.31s/it]

 75%|████████████████████████████████████████████████████████████▋                    | 369/493 [07:28<02:31,  1.22s/it]

 75%|████████████████████████████████████████████████████████████▊                    | 370/493 [07:29<02:22,  1.16s/it]

 75%|████████████████████████████████████████████████████████████▉                    | 371/493 [07:29<02:02,  1.00s/it]

 75%|█████████████████████████████████████████████████████████████                    | 372/493 [07:31<02:24,  1.19s/it]

 76%|█████████████████████████████████████████████████████████████▎                   | 373/493 [07:32<02:38,  1.32s/it]

 76%|█████████████████████████████████████████████████████████████▍                   | 374/493 [07:34<02:33,  1.29s/it]

 76%|█████████████████████████████████████████████████████████████▌                   | 375/493 [07:35<02:20,  1.19s/it]

 76%|█████████████████████████████████████████████████████████████▊                   | 376/493 [07:36<02:17,  1.17s/it]

 76%|█████████████████████████████████████████████████████████████▉                   | 377/493 [07:37<02:32,  1.31s/it]

 77%|██████████████████████████████████████████████████████████████                   | 378/493 [07:38<02:19,  1.21s/it]

 77%|██████████████████████████████████████████████████████████████▎                  | 379/493 [07:40<02:31,  1.33s/it]

 77%|██████████████████████████████████████████████████████████████▍                  | 380/493 [07:41<02:05,  1.11s/it]

 77%|██████████████████████████████████████████████████████████████▌                  | 381/493 [07:42<02:20,  1.26s/it]

 77%|██████████████████████████████████████████████████████████████▊                  | 382/493 [07:44<02:31,  1.37s/it]

 78%|██████████████████████████████████████████████████████████████▉                  | 383/493 [07:45<02:21,  1.29s/it]

 78%|███████████████████████████████████████████████████████████████                  | 384/493 [07:47<02:31,  1.39s/it]

 78%|███████████████████████████████████████████████████████████████▎                 | 385/493 [07:48<02:38,  1.47s/it]

 78%|███████████████████████████████████████████████████████████████▍                 | 386/493 [07:50<02:42,  1.51s/it]

 78%|███████████████████████████████████████████████████████████████▌                 | 387/493 [07:51<02:38,  1.49s/it]

 79%|███████████████████████████████████████████████████████████████▋                 | 388/493 [07:52<02:27,  1.40s/it]

 79%|███████████████████████████████████████████████████████████████▉                 | 389/493 [07:54<02:33,  1.47s/it]

 79%|████████████████████████████████████████████████████████████████                 | 390/493 [07:55<02:24,  1.41s/it]

 79%|████████████████████████████████████████████████████████████████▏                | 391/493 [07:57<02:30,  1.48s/it]

 80%|████████████████████████████████████████████████████████████████▍                | 392/493 [07:58<02:26,  1.45s/it]

 80%|████████████████████████████████████████████████████████████████▌                | 393/493 [08:00<02:22,  1.42s/it]

 80%|████████████████████████████████████████████████████████████████▋                | 394/493 [08:01<02:18,  1.40s/it]

 80%|████████████████████████████████████████████████████████████████▉                | 395/493 [08:02<01:55,  1.18s/it]

 80%|█████████████████████████████████████████████████████████████████                | 396/493 [08:03<01:50,  1.14s/it]

 81%|█████████████████████████████████████████████████████████████████▏               | 397/493 [08:04<01:51,  1.16s/it]

 81%|█████████████████████████████████████████████████████████████████▍               | 398/493 [08:05<01:51,  1.17s/it]

 81%|█████████████████████████████████████████████████████████████████▌               | 399/493 [08:06<01:50,  1.17s/it]

 81%|█████████████████████████████████████████████████████████████████▋               | 400/493 [08:07<01:34,  1.01s/it]

 81%|█████████████████████████████████████████████████████████████████▉               | 401/493 [08:08<01:40,  1.10s/it]

 82%|██████████████████████████████████████████████████████████████████               | 402/493 [08:10<01:54,  1.26s/it]

 82%|██████████████████████████████████████████████████████████████████▏              | 403/493 [08:11<01:51,  1.24s/it]

 82%|██████████████████████████████████████████████████████████████████▍              | 404/493 [08:12<01:41,  1.14s/it]

 82%|██████████████████████████████████████████████████████████████████▌              | 405/493 [08:13<01:39,  1.13s/it]

 82%|██████████████████████████████████████████████████████████████████▋              | 406/493 [08:15<01:52,  1.29s/it]

 83%|██████████████████████████████████████████████████████████████████▊              | 407/493 [08:16<01:48,  1.27s/it]

 83%|███████████████████████████████████████████████████████████████████              | 408/493 [08:17<01:51,  1.31s/it]

 83%|███████████████████████████████████████████████████████████████████▏             | 409/493 [08:19<01:57,  1.40s/it]

 83%|███████████████████████████████████████████████████████████████████▎             | 410/493 [08:20<01:55,  1.39s/it]

 83%|███████████████████████████████████████████████████████████████████▌             | 411/493 [08:21<01:45,  1.29s/it]

 84%|███████████████████████████████████████████████████████████████████▋             | 412/493 [08:22<01:34,  1.16s/it]

 84%|███████████████████████████████████████████████████████████████████▊             | 413/493 [08:23<01:28,  1.11s/it]

 84%|████████████████████████████████████████████████████████████████████             | 414/493 [08:25<01:30,  1.14s/it]

 84%|████████████████████████████████████████████████████████████████████▏            | 415/493 [08:25<01:24,  1.08s/it]

 84%|████████████████████████████████████████████████████████████████████▎            | 416/493 [08:27<01:31,  1.19s/it]

 85%|████████████████████████████████████████████████████████████████████▌            | 417/493 [08:28<01:36,  1.27s/it]

 85%|████████████████████████████████████████████████████████████████████▋            | 418/493 [08:29<01:30,  1.20s/it]

 85%|████████████████████████████████████████████████████████████████████▊            | 419/493 [08:31<01:31,  1.23s/it]

 85%|█████████████████████████████████████████████████████████████████████            | 420/493 [08:32<01:21,  1.12s/it]

 85%|█████████████████████████████████████████████████████████████████████▏           | 421/493 [08:32<01:12,  1.00s/it]

 86%|█████████████████████████████████████████████████████████████████████▎           | 422/493 [08:33<01:11,  1.01s/it]

 86%|█████████████████████████████████████████████████████████████████████▍           | 423/493 [08:35<01:16,  1.09s/it]

 86%|█████████████████████████████████████████████████████████████████████▋           | 424/493 [08:36<01:24,  1.23s/it]

 86%|█████████████████████████████████████████████████████████████████████▊           | 425/493 [08:38<01:32,  1.37s/it]

 86%|█████████████████████████████████████████████████████████████████████▉           | 426/493 [08:40<01:38,  1.46s/it]

 87%|██████████████████████████████████████████████████████████████████████▏          | 427/493 [08:41<01:29,  1.35s/it]

 87%|██████████████████████████████████████████████████████████████████████▎          | 428/493 [08:42<01:25,  1.32s/it]

 87%|██████████████████████████████████████████████████████████████████████▍          | 429/493 [08:43<01:28,  1.39s/it]

 87%|██████████████████████████████████████████████████████████████████████▋          | 430/493 [08:44<01:18,  1.24s/it]

 87%|██████████████████████████████████████████████████████████████████████▊          | 431/493 [08:46<01:17,  1.24s/it]

 88%|██████████████████████████████████████████████████████████████████████▉          | 432/493 [08:47<01:22,  1.36s/it]

 88%|███████████████████████████████████████████████████████████████████████▏         | 433/493 [08:49<01:21,  1.36s/it]

 88%|███████████████████████████████████████████████████████████████████████▎         | 434/493 [08:50<01:16,  1.29s/it]

 88%|███████████████████████████████████████████████████████████████████████▍         | 435/493 [08:51<01:08,  1.17s/it]

 88%|███████████████████████████████████████████████████████████████████████▋         | 436/493 [08:52<01:02,  1.10s/it]

 89%|███████████████████████████████████████████████████████████████████████▊         | 437/493 [08:52<00:59,  1.06s/it]

 89%|███████████████████████████████████████████████████████████████████████▉         | 438/493 [08:53<00:55,  1.01s/it]

 89%|████████████████████████████████████████████████████████████████████████▏        | 439/493 [08:54<00:52,  1.04it/s]

 89%|████████████████████████████████████████████████████████████████████████▎        | 440/493 [08:55<00:51,  1.03it/s]

 89%|████████████████████████████████████████████████████████████████████████▍        | 441/493 [08:57<00:55,  1.07s/it]

 90%|████████████████████████████████████████████████████████████████████████▌        | 442/493 [08:58<00:54,  1.08s/it]

 90%|████████████████████████████████████████████████████████████████████████▊        | 443/493 [08:59<01:01,  1.24s/it]

 90%|████████████████████████████████████████████████████████████████████████▉        | 444/493 [09:01<01:04,  1.32s/it]

 90%|█████████████████████████████████████████████████████████████████████████        | 445/493 [09:02<01:02,  1.31s/it]

 90%|█████████████████████████████████████████████████████████████████████████▎       | 446/493 [09:03<01:02,  1.33s/it]

 91%|█████████████████████████████████████████████████████████████████████████▍       | 447/493 [09:05<01:04,  1.40s/it]

 91%|█████████████████████████████████████████████████████████████████████████▌       | 448/493 [09:06<00:53,  1.18s/it]

 91%|█████████████████████████████████████████████████████████████████████████▊       | 449/493 [09:07<00:49,  1.13s/it]

 91%|█████████████████████████████████████████████████████████████████████████▉       | 450/493 [09:08<00:51,  1.20s/it]

 91%|██████████████████████████████████████████████████████████████████████████       | 451/493 [09:09<00:46,  1.10s/it]

 92%|██████████████████████████████████████████████████████████████████████████▎      | 452/493 [09:10<00:50,  1.24s/it]

 92%|██████████████████████████████████████████████████████████████████████████▍      | 453/493 [09:12<00:54,  1.36s/it]

 92%|██████████████████████████████████████████████████████████████████████████▌      | 454/493 [09:13<00:48,  1.24s/it]

 92%|██████████████████████████████████████████████████████████████████████████▊      | 455/493 [09:14<00:42,  1.13s/it]

 92%|██████████████████████████████████████████████████████████████████████████▉      | 456/493 [09:15<00:43,  1.18s/it]

 93%|███████████████████████████████████████████████████████████████████████████      | 457/493 [09:16<00:40,  1.13s/it]

 93%|███████████████████████████████████████████████████████████████████████████▏     | 458/493 [09:18<00:44,  1.27s/it]

 93%|███████████████████████████████████████████████████████████████████████████▍     | 459/493 [09:19<00:41,  1.22s/it]

 93%|███████████████████████████████████████████████████████████████████████████▌     | 460/493 [09:20<00:34,  1.06s/it]

 94%|███████████████████████████████████████████████████████████████████████████▋     | 461/493 [09:21<00:39,  1.23s/it]

 94%|███████████████████████████████████████████████████████████████████████████▉     | 462/493 [09:22<00:35,  1.14s/it]

 94%|████████████████████████████████████████████████████████████████████████████     | 463/493 [09:24<00:38,  1.28s/it]

 94%|████████████████████████████████████████████████████████████████████████████▏    | 464/493 [09:25<00:36,  1.28s/it]

 94%|████████████████████████████████████████████████████████████████████████████▍    | 465/493 [09:26<00:35,  1.28s/it]

 95%|████████████████████████████████████████████████████████████████████████████▌    | 466/493 [09:27<00:33,  1.24s/it]

 95%|████████████████████████████████████████████████████████████████████████████▋    | 467/493 [09:29<00:30,  1.19s/it]

 95%|████████████████████████████████████████████████████████████████████████████▉    | 468/493 [09:29<00:25,  1.02s/it]

 95%|█████████████████████████████████████████████████████████████████████████████    | 469/493 [09:31<00:27,  1.15s/it]

 95%|█████████████████████████████████████████████████████████████████████████████▏   | 470/493 [09:32<00:29,  1.29s/it]

 96%|█████████████████████████████████████████████████████████████████████████████▍   | 471/493 [09:34<00:30,  1.39s/it]

 96%|█████████████████████████████████████████████████████████████████████████████▌   | 472/493 [09:35<00:26,  1.25s/it]

 96%|█████████████████████████████████████████████████████████████████████████████▋   | 473/493 [09:36<00:23,  1.19s/it]

 96%|█████████████████████████████████████████████████████████████████████████████▉   | 474/493 [09:37<00:23,  1.25s/it]

 96%|██████████████████████████████████████████████████████████████████████████████   | 475/493 [09:38<00:22,  1.24s/it]

 97%|██████████████████████████████████████████████████████████████████████████████▏  | 476/493 [09:40<00:21,  1.28s/it]

 97%|██████████████████████████████████████████████████████████████████████████████▎  | 477/493 [09:41<00:18,  1.14s/it]

 97%|██████████████████████████████████████████████████████████████████████████████▌  | 478/493 [09:42<00:16,  1.11s/it]

 97%|██████████████████████████████████████████████████████████████████████████████▋  | 479/493 [09:43<00:17,  1.26s/it]

 97%|██████████████████████████████████████████████████████████████████████████████▊  | 480/493 [09:44<00:16,  1.23s/it]

 98%|███████████████████████████████████████████████████████████████████████████████  | 481/493 [09:46<00:16,  1.35s/it]

 98%|███████████████████████████████████████████████████████████████████████████████▏ | 482/493 [09:47<00:14,  1.34s/it]

 98%|███████████████████████████████████████████████████████████████████████████████▎ | 483/493 [09:49<00:12,  1.30s/it]

 98%|███████████████████████████████████████████████████████████████████████████████▌ | 484/493 [09:50<00:11,  1.33s/it]

 98%|███████████████████████████████████████████████████████████████████████████████▋ | 485/493 [09:51<00:10,  1.34s/it]

 99%|███████████████████████████████████████████████████████████████████████████████▊ | 486/493 [09:53<00:09,  1.29s/it]

 99%|████████████████████████████████████████████████████████████████████████████████ | 487/493 [09:54<00:07,  1.26s/it]

 99%|████████████████████████████████████████████████████████████████████████████████▏| 488/493 [09:55<00:05,  1.19s/it]

 99%|████████████████████████████████████████████████████████████████████████████████▎| 489/493 [09:56<00:04,  1.23s/it]

 99%|████████████████████████████████████████████████████████████████████████████████▌| 490/493 [09:58<00:04,  1.35s/it]

100%|████████████████████████████████████████████████████████████████████████████████▋| 491/493 [09:59<00:02,  1.33s/it]

100%|████████████████████████████████████████████████████████████████████████████████▊| 492/493 [10:01<00:01,  1.42s/it]

100%|█████████████████████████████████████████████████████████████████████████████████| 493/493 [10:01<00:00,  1.13s/it]

100%|█████████████████████████████████████████████████████████████████████████████████| 493/493 [10:01<00:00,  1.22s/it]

In [35]:
result = compute_metrics(output_sequences, tokenized_datasets["test"]["labels"], all_sources)
print(f'BLEU score: {result["bleu"]:0.4f}')
print(f'COMET score: {result["comet"]:0.4f}')
print(f'CHRF score: {result["chrf"]:0.4f}')

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/venv/lib/python3.12/site-packages/torch/__init__.py:1551: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:80.)
  return _C._get_float32_matmul_precision()
You are using a CUDA device ('NVIDIA GeForce RTX 5070') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

BLEU score: 20.7225
COMET score: 0.7221
CHRF score: 47.1243

In [36]:
from maikol_utils.print_utils import print_separator

# all_sources already contains raw text strings
# output_sequences contains token IDs that need to be decoded
decoded_outputs = tokenizer.batch_decode(output_sequences, skip_special_tokens=True)

# Get reference translations from test set
test_references = tokenized_datasets["test"]["dest_text"]

# Print first 10 examples
for i, (source, output, reference) in enumerate(zip(all_sources[:10], decoded_outputs[:10], test_references[:10])):
    print_separator(f"Example {i+1}:")
    print(f"Source:      {source}")
    print(f"Translation: {output}")
    print(f"Reference:   {reference}")

________________________________________________________________
                           Example 1:

Source:      usted, amigo oyente, no está muy
Translation: , amiko aŭskultanto, ne estas tiel granda.
Reference:   cxu vi, amiko, ne tre povas
________________________________________________________________
                           Example 2:

Source:      doctor en filología hispanica.
Translation: estas doktoro en hispana lingvo.
Reference:   magistro pri hispana filologio.
________________________________________________________________
                           Example 3:

Source:      sentía en mi alma el eco de la pregunta dirigida entonces a pedro: “¿me amas?
Translation: s en mia animo la econ de la demando direktita al pedro: ĉu vi amas min?
Reference:   mi sentis en mia animo la eĥon de la demando tiam adresita al petro: “ĉu vi amas min?
________________________________________________________________
                           Example 4:

Source:      con jekyll era una especie de instinto vital.
Translation: estis iu speco de vitala instinto.
Reference:   ĉe jekyll, ĝi estis afero de esenca instinkto.
________________________________________________________________
                           Example 5:

Source:      información sobre el puerto de fort lauderdale
Translation: s o fort lauderdale portu
Reference:   jakto en la haveno de fort lauderdale
________________________________________________________________
                           Example 6:

Source:      cuando yo era muy joven mi madre me preguntó cuál era la parte más importante del cuerpo.
Translation: kiam mi estis juna, mia patrino demandis min kio estis la plej grava parto de la korpo.
Reference:   kiam mi estis infaneca, mia patrino foje demandis min, kiu parto estas la plej grava sur homa korpo?
________________________________________________________________
                           Example 7:

Source:      de lo contrario, no habría arriesgado su vida?.
Translation: , se ŝi ne riskus sian vivon?
Reference:   junulinon; li ne estis freneza riskigi sian vivon.
________________________________________________________________
                           Example 8:

Source:      ahora yo vivo en canada con mi familia.
Translation: mi nun loĝas en kanado kun mia familia.
Reference:   sed, nun mi loĝas en la an-san kun mia familio.
________________________________________________________________
                           Example 9:

Source:      el equipo tampoco detectó diferencias de acuerdo con el peso o la etnia materna, el género de los niños o la cantidad de gaseosa que consumían los niños.
Translation: estis ankaŭ ne detektita laŭ la aĝo aŭ la patrina etneco, la sekso de la infanoj, aŭ la kvanto de gaso konsumita fare de la infanoj.
Reference:   la teamo de esploro ankaŭ ne vidis diferencojn bazitajn sur la pezo, raso aŭ etna origino de la patrino, la sekso de la infano aŭ la kvanto da soda infanoj mem trinkis.
________________________________________________________________
                          Example 10:

Source:      a veces hay situaciones en las que esto tiene que ser defendido y otros miembros de la comunidad necesitan ayuda.
Translation: estas ofte okazaĵoj, kie tio devas esti defendita kaj aliaj membroj de la komunumo bezonas helpon.
Reference:   kelkfoje tiuj valoroj devas esti defendataj kaj aliaj komunumaj membroj povas bezoni helpon por tio.